name: Build and deploy

permissions:
  contents: write
  packages: write
  deployments: write

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images (x64)
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache-x64
          cache-to: type=local,dest=/tmp/.buildx-cache-x64-new
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64

      - name: Build and push Docker images (arm64)
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache-arm64
          cache-to: type=local,dest=/tmp/.buildx-cache-arm64-new
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/arm64

      - name: Move cache (x64)
        run: |
          rm -rf /tmp/.buildx-cache-x64
          mv /tmp/.buildx-cache-x64-new /tmp/.buildx-cache-x64

      - name: Move cache (arm64)
        run: |
          rm -rf /tmp/.buildx-cache-arm64
          mv /tmp/.buildx-cache-arm64-new /tmp/.buildx-cache-arm64
